on: push
jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v3
      - run: npm install
      - name: Change Directory
        shell: bash
        run: cd ./frontend
      - run: npm ci
      - name: build
        shell: bash
        run: npm run build --if-present
      - name: Change Directory
        shell: bash
        run: cd ./
      - name: Change Directory
        shell: bash
        run: npm start
      

