name: Nodejs CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: [self-hosted,Linux]
    steps:
    # - name: git checkout  
    #   uses: actions/checkout@v2
    # - name: Use Node.js ${{matrix.node-version}}
    #   uses: actions/setup-node@v2
    #   with:
    #     node-version: ${{matrix.node-version}}
    - run:
        pwd
        ls 
        # npm install
        # cd frontend
        # npm install
        # npm run build 
      

