name: Nodejs CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: [self-hosted,Linux]
    steps:
    - name: git checkout  
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.20.0 
    - run:
        pwd ~/.bashrc
        cat app.js ~/.bashrc
        cd frontend ~/.bashrc
        echo "hello world" ~/.bashrc
        pwd ~/.bashrc
      

